### ISSUE TITLE
jaccard issue

### ISSUE THREAD

**Issue by desireetillo** [CCBR/CCBR_ATACseq#5]
Issue with jaccard: genrich uses a non-canonical sorting for peak files (i.e. not name sorted,but numeric by chromosome).

 This causes jaccard on consensus files step to fail in comparing samples with only 1 replicate to those with replicates.  For the consensus peak file for samples with replicates (name sorted), while it's not for the single replicate.  To be on safe side -- do a bedsort on the consensus bedfile in cases where nrep=1

 (e.g. line 186 of ccbr_atac_genrich_peak_calling.bash   cut -f1-3 $PEAKFILE1 | sort -k1,1 -k2,2n > $CONSENSUSBEDFILE)

**Comment by kopardev** [comment]
Fixed in https://github.com/CCBR/CCBR_ATACseq/commit/62809a0b371022537983e28a7a199d103cf5f11c
